export const SET_CURRENT_USER = "SET_CURRENT_USER"
export const SET_USER_TOKEN = "SET_USER_TOKEN"
export const CLEAR_CURRENT_USER = "CLEAR_CURRENT_USER"
export const FAILED_REGISTER = 'FAILED_REGISTER'
export const FAILED_LOGIN = 'FAILED_LOGIN'
export const REGISTER = "REGISTER"
export const LOGIN = "LOGIN"
export const LOGOUT = "LOGOUT"

export const SET_LOCALE = "SET_LOCALE"

export const LOAD_MEASURES = "LOAD_MEASURES"
export const FAILED_LOAD_MEASURES = "FAILED_LOAD_MEASURES"
export const CLEAR_MEASURES = "CLEAR_MEASURES"


export const LOAD_STEPS = "LOAD_STEPS"
export const FAILED_LOAD_STEPS = "FAILED_LOAD_STEPS"
export const CLEAR_STEPS = "CLEAR_STEPS"

export const LOAD_PULSE = "LOAD_PULSE"
export const CLEAR_PULSE = "CLEAR_PULSE"


export const SET_DISCOUNT = "SET_DISCOUNT"
export const CLEAR_DISCOUNT = "CLEAR_DISCOUNT"
