export const SET_CURRENT_USER = "SET_CURRENT_USER"
export const SET_USER_TOKEN = "SET_USER_TOKEN"
export const CLEAR_CURRENT_USER = "CLEAR_CURRENT_USER"
export const FAILED_REGISTER = 'FAILED_REGISTER'
export const FAILED_LOGIN = 'FAILED_LOGIN'
export const REGISTER = "REGISTER"
export const LOGIN = "LOGIN"
export const LOGOUT = "LOGOUT"

export const SET_LOCALE = "SET_LOCALE"

export const LOAD_MEASURES = "LOAD_MEASURES"
export const FAILED_LOAD_MEASURES = "FAILED_LOAD_MEASURES"
export const CLEAR_MEASURES = "CLEAR_MEASURES"
